version: '2.1'

services:
  server:
    extends:
      file: docker-compose.base.yml
      service: base-django
    ports:
      - 8050:8000
    depends_on:
      - db
      - broker
      - worker
    command: python3 manage.py runserver 0.0.0.0:8000
  scheduler:
    extends:
      file: docker-compose.base.yml
      service: base-django
    depends_on:
      - db
      - broker
    command: bash -c "DJANGO_SETTINGS_MODULE=tm.settings celery -A tm beat --scheduler django_celery_beat.schedulers:DatabaseScheduler --pidfile /celerybeat.pid"
  worker:
    extends:
      file: docker-compose.base.yml
      service: base-django
    depends_on:
      - db
      - broker
    command: bash -c "DJANGO_SETTINGS_MODULE=tm.settings celery -A tm worker"
  broker:
    image: redis
    networks:
      - tm-network
  db:
    image: postgres:9.6
    ports:
      - 5432:5432
    networks:
      - tm-network
    volumes:
      - pgdata:/var/lib/postgresql/data

networks:
  tm-network:
    external: true

volumes:
  pgdata:
