version: '2.1'

services:
  server:
    extends:
      file: docker-compose.base.yml
      service: base-django
    ports:
      - 8050:8000
    command: ./manage.py runserver -p 8000
  scheduler:
    extends:
      file: docker-compose.base.yml
      service: base-django
  worker-1:
    extends:
      file: docker-compose.base.yml
      service: base-django
  worker-2:
    extends:
      file: docker-compose.base.yml
      service: base-django
  broker:
    image: redis
  db:
    image: postgres
